efs/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.urls import path
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    url(r'^accounts/login/$', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(template_name='registration/logout.html'), name='logout', kwargs={'next_page': '/'}),
]

portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
#from django.contrib.auth.views import PasswordChangeView as pwd_change, PasswordChangeDoneView as pwd_change_done, PasswordResetView as reset, PasswordResetDoneView as reset_done, PasswordResetConfirmView as reset_confirm, PasswordResetCompleteView as reset_complete
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'portfolio'
urlpatterns = [

    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),

    url(r'^register/$', views.register, name='register'),

    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('portfolio:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('portfolio:password_reset_done')), {'email_template_name': 'registration/password_reset_email.html'}, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('portfolio:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    url(r'^customers_json/', views.CustomerList.as_view()),
    path('customer/<int:pk>/portfolio/pdf/', views.customer_portfolio_pdf, name='customer_portfolio_pdf'),
    path('customer/<int:pk>/portfolio/email_pdf/', views.customer_portfolio_email_pdf, name='customer_portfolio_email_pdf'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/models.py
from django.db import models

from django.utils import timezone
import requests


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value


class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField (max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price

    def current_stock_price(self):
        symbol_f = str(self.symbol)
        main_api = 'https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&symbols='
        api_key = '&apikey= S2V22ICTUQKT50AM'
        url = main_api + symbol_f + api_key
        json_data = requests.get(url).json()
        open_price = float(json_data["Stock Quotes"][0]["2. price"])
        share_value = open_price
        return share_value

    def current_stock_value(self):
        return float(self.current_stock_price()) * float(self.shares)

portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment
from django.contrib.auth.models import User


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class StockForm(forms.ModelForm):
   class Meta:
       model = Stock
       fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)


class InvestmentForm(forms.ModelForm):
   class Meta:
       model = Investment
       fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value', 'recent_date',)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

portfolio/views.py
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
#import weasyprint
#from weasyprint import HTML, CSS
from django.template.loader import get_template
from easy_pdf.rendering import render_to_pdf
from django.core.mail import EmailMessage
from django.urls import reverse

now = timezone.now()
def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
            user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'portfolio/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
        return render(request, 'portfolio/register.html', {'user_form': user_form})


@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})


@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('portfolio:customer_list')


@login_required
def stock_list(request):
   stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@login_required
def stock_new(request):
   if request.method == "POST":
       form = StockForm(request.POST)
       if form.is_valid():
           stock = form.save(commit=False)
           stock.created_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html',
                         {'stocks': stocks})
   else:
       form = StockForm()
       # print("Else")
   return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   if request.method == "POST":
       form = StockForm(request.POST, instance=stock)
       if form.is_valid():
           stock = form.save()
           # stock.customer = stock.id
           stock.updated_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
   else:
       # print("else")
       form = StockForm(instance=stock)
   return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   stock.delete()
   return redirect('portfolio:stock_list')


@login_required
def investment_list(request):
   investments = Investment.objects.filter(recent_date__lte=timezone.now())
   return render(request, 'portfolio/investment_list.html', {'investments': investments})


@login_required
def investment_new(request):
   if request.method == "POST":
       form = InvestmentForm(request.POST)
       if form.is_valid():
           investment = form.save(commit=False)
           investment.created_date = timezone.now()
           investment.save()
           investments = Investment.objects.filter(recent_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html',
                         {'investments': investments})
   else:
       form = InvestmentForm()
       # print("Else")
   return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def investment_edit(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   if request.method == "POST":
       form = InvestmentForm(request.POST, instance=investment)
       if form.is_valid():
           investment = form.save()
           # investment.customer = investment.id
           investment.updated_date = timezone.now()
           investment.save()
           investments = Investment.objects.filter(recent_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html', {'investments': investments})
   else:
       # print("else")
       form = InvestmentForm(instance=investment)
   return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   investment.delete()
   return redirect('portfolio:investment_list')


@login_required
def portfolio(request,pk):
   customer = get_object_or_404(Customer, pk=pk)
   customers = Customer.objects.filter(created_date__lte=timezone.now())
   investments =Investment.objects.filter(customer=pk)
   stocks = Stock.objects.filter(customer=pk)
   sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
   sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
   #overall_investment_results = sum_recent_value-sum_acquired_value
   # Initialize the value of the stocks
   sum_current_stocks_value = 0
   sum_of_initial_stock_value = 0

   # Loop through each stock and add the value to the total
   for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

   #sum_of_init_stock_investment = sum_of_initial_stock_value + sum_acquired_value
   return render(request, 'portfolio/portfolio.html', {'customers': customers,
                                                       'investments': investments,
                                                       'stocks': stocks,
                                                       'sum_acquired_value': sum_acquired_value,
                                                       'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        })

# Lists all customers
class CustomerList(APIView):

    def get(self,request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)
        return Response(serializer.data)


@login_required
def customer_portfolio_pdf(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    template = get_template('portfolio/customer_portfolio_pdf.html')
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    # overall_investment_results = sum_recent_value-sum_acquired_value
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    context = {
        'customer':customers,
        'investments':investments,
        'stocks':stocks,
        'sum_acquired_value':sum_acquired_value,
        'sum_recent_value':sum_recent_value,
        'sum_current_stocks_value':sum_current_stocks_value,
        'sum_of_initial_stock_value':sum_of_initial_stock_value,
    }

    #generate pdf
    html = template.render(context)
    pdf = render_to_pdf('portfolio/customer_portfolio_pdf.html', context)
    if pdf:
        response =HttpResponse(pdf, content_type='application/customer_portfolio_pdf')
        filename = 'customer_portfolio_' + str(customer.cust_number) + '.pdf'
        content = "inline; filename='%s'" % (filename)
        download = request.GET.get("download")
        if download:
            content = "attachment; filename='%s'" % (filename)
        response['Content-Disposition'] = content
        return response
    return HttpResponse("not found")


@login_required
def customer_portfolio_email_pdf(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)

portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="5">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                    <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio</a></td>
                    <td><a href="{% url 'portfolio:customer_portfolio_pdf' pk=customer.pk %}"
                           class="btn btn-primary">Generate PDF</a></td>
                    <td><a href="{% url 'portfolio:customer_portfolio_email_pdf' pk=customer.pk %}"
                           class="btn btn-primary">Email PDF</a></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/customer_portfolio_pdf.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>


{% block content %}
{% load humanize %}
{% load mathfilters %}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Eagle Financial Services</div>
                <div class="panel-body">
                    Midwest Financial Service Partner!
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <h1 style="padding-left: 15Px">Customer Portfolio</h1>
</div>

<div class="row">
    <h2 style="padding-left: 15Px">Overall Portfolio Performance</h2>
</div>

    <div class="row">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Portfolio Initial Investments</th>
            <th>Portfolio Current Investments</th>
            <th>Grand Total Results</th>

        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ sum_of_initial_stock_value|add:sum_acquired_value.acquired_value__sum|intcomma }}</td>
                <td>{{ sum_current_stocks_value|add:sum_recent_value.recent_value__sum|intcomma }}</td>
                <td>{{ sum_current_stocks_value|add:sum_recent_value.recent_value__sum|sub:sum_of_initial_stock_value|sub:sum_acquired_value.acquired_value__sum|intcomma }}</td>
            </tr>
        </tbody>
    </table>
    </div>

<div class="row">
    <h2 style="padding-left: 15Px">Stocks Information</h2>
</div>
    <div class="row">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th scope="col">Customer</th>
            <th scope="col">Symbol</th>
            <th scope="col">Name</th>
            <th scope="col">Shares</th>
            <th scope="col">Initial Stock Price</th>
            <th scope="col">Initial Stock Value</th>
            <th scope="col">Current Stock Price</th>
            <th colspan="2">Current Stock Value</th>
            <th colspan="2">Results</th>
        </tr>
        </thead>
        <tbody>
        {% for stock in stocks %}
            <tr>
                <td>{{ stock.customer }}</td>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.name }}</td>
                <td>{{ stock.shares|intcomma }}</td>
                <td>{{ stock.purchase_price|intcomma }}</td>
                <td>{{ stock.initial_stock_value|intcomma }}</td>
                <td>{{ stock.current_stock_price|intcomma }}</td>
                <td>{{ stock.current_stock_value|intcomma }}</td>
                <td>{{ stock.current_stock_value|sub:stock.initial_stock_value|intcomma }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Total of Initial Stocks</th>
            <th>Total of Current Stocks</th>
            <th>Results</th>

        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ sum_of_initial_stock_value|intcomma }}</td>
                <td>{{ sum_current_stocks_value|intcomma }}</td>
                <td>{{ sum_current_stocks_value|sub:sum_of_initial_stock_value|intcomma }}</td>
            </tr>
        </tbody>
    </table>
    </div>


<div class="row">
    <h2 style="padding-left: 15Px">Investment Information</h2>
</div>
<div class="row">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th scope="col">Customer</th>
            <th scope="col">Category</th>
            <th scope="col">Description</th>
            <th scope="col">Acquired Value</th>
            <th scope="col">Acquired Date</th>
            <th scope="col">Recent Value</th>
            <th scope="col">Recent Date</th>
            <th scope="col">Results</th>

        </tr>
        </thead>
        <tbody>
        {% for investment in investments %}
            <tr>
                <td>{{ investment.customer }}</td>
                <td>{{ investment.category }}</td>
                <td>{{ investment.description }}</td>
                <td>{{ investment.acquired_value }}</td>
                <td>{{ investment.acquired_date }}</td>
                <td>{{ investment.recent_value }}</td>
                <td>{{ investment.recent_date }}</td>
                <td>{{ investment.results_by_investment }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Total of Initial Investments</th>
            <th>Total of Current Investments</th>
            <th>Results</th>

        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ sum_acquired_value.acquired_value__sum|intcomma }}</td>
                <td>{{ sum_recent_value.recent_value__sum|intcomma }}</td>
                <td>{{ sum_recent_value.recent_value__sum|sub:sum_acquired_value.acquired_value__sum|intcomma }}</td>
            </tr>
        </tbody>
    </table>

    </div>

{% endblock %}

portfolio/templates/portfolio/investment_delete.html
{% extends 'portfolio/base.html' %}
 {% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=customer.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Investments Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired Value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for investment in investments %}
                <tr>
                    <td>{{ investment.customer }}</td>
                    <td>{{ investment.category }}</td>
                    <td>{{ investment.description }}</td>
                    <td>{{ investment.acquired_value }}</td>
                    <td>{{ investment.acquired_date }}</td>
                    <td>{{ investment.recent_value }}</td>
                    <td>{{ investment.recent_date }}</td>
                    <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
         <a href="{% url 'portfolio:investment_new' %}" class="row"><span
                    class="btn btn-primary">Add Investment</span></a>
     </div>

    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/stock_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Stocks Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer number</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Shares</th>
                <th>Purchase Price</th>
                <th>Purchase Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for stock in stocks %}
                <tr>
                    <td>{{ stock.customer }}</td>
                    <td>{{ stock.symbol }}</td>
                    <td>{{ stock.name }}</td>
                    <td>{{ stock.shares }}</td>
                    <td>{{ stock.purchase_price }}</td>
                    <td>{{ stock.purchase_date }}</td>
                    <td><a href="{% url 'portfolio:stock_edit' pk=stock.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:stock_delete' pk=stock.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
         <a href="{% url 'portfolio:stock_new' %}" class="row"><span
                    class="btn btn-primary">Add Stock</span></a>
     </div>

    </div>
    </body>
    </html>
{% endblock %}